[build]
builder = "nixpacks"
buildCommand = "npm install && npm run install-client && npm run build-client"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicy = "on-failure"
numReplicas = 1 