[build]
builder = "nixpacks"
buildCommand = "npm install && npm run install-client && npm run build-client"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 180
restartPolicy = "on-failure"
numReplicas = 1 